package com.prodigit.web.coffee.model;

// Generated 1/05/2011 12:57:56 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer idcategory;
	private String dscategory;
	private int lft;
	private int rgt;
	private Set products = new HashSet(0);

	public Category() {
	}

	public Category(String dscategory, int lft, int rgt) {
		this.dscategory = dscategory;
		this.lft = lft;
		this.rgt = rgt;
	}

	public Category(String dscategory, int lft, int rgt, Set products) {
		this.dscategory = dscategory;
		this.lft = lft;
		this.rgt = rgt;
		this.products = products;
	}

	public Integer getIdcategory() {
		return this.idcategory;
	}

	public void setIdcategory(Integer idcategory) {
		this.idcategory = idcategory;
	}

	public String getDscategory() {
		return this.dscategory;
	}

	public void setDscategory(String dscategory) {
		this.dscategory = dscategory;
	}

	public int getLft() {
		return this.lft;
	}

	public void setLft(int lft) {
		this.lft = lft;
	}

	public int getRgt() {
		return this.rgt;
	}

	public void setRgt(int rgt) {
		this.rgt = rgt;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
