package com.prodigit.web.coffee.model;

// Generated 1/05/2011 12:57:56 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;


/**
 * Itemcart generated by hbm2java
 */
public class Itemcart implements java.io.Serializable {

	private Integer iditemcart;
	private Price price;
	private Cart cart;
	private Integer qty;

	public Itemcart() {
	}

	public Itemcart(Price price, Cart cart, Integer qty) {
		this.price = price;
		this.cart = cart;
		this.qty = qty;
	}

	public Integer getIditemcart() {
		return this.iditemcart;
	}

	public void setIditemcart(Integer iditemcart) {
		this.iditemcart = iditemcart;
	}

	public Price getPrice() {
		return this.price;
	}

	public void setPrice(Price price) {
		this.price = price;
	}

	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

}
