package com.prodigit.web.coffee.model;

// Generated 1/05/2011 12:57:56 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Price generated by hbm2java
 */
public class Price implements java.io.Serializable {

	private Integer idprice;
	private Market market;
	private Product product;
	private BigDecimal price;
	private Set itemcarts = new HashSet(0);

	public Price() {
	}

	public Price(Market market, Product product) {
		this.market = market;
		this.product = product;
	}

	public Price(Market market, Product product, BigDecimal price, Set itemcarts) {
		this.market = market;
		this.product = product;
		this.price = price;
		this.itemcarts = itemcarts;
	}

	public Integer getIdprice() {
		return this.idprice;
	}

	public void setIdprice(Integer idprice) {
		this.idprice = idprice;
	}

	public Market getMarket() {
		return this.market;
	}

	public void setMarket(Market market) {
		this.market = market;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Set getItemcarts() {
		return this.itemcarts;
	}

	public void setItemcarts(Set itemcarts) {
		this.itemcarts = itemcarts;
	}

}
