package com.prodigit.web.coffee.model;

// Generated 1/05/2011 12:57:56 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer idproduct;
	private String dsproduct;
	private String txproduct;
	private Set prices = new HashSet(0);
	private Set categories = new HashSet(0);
	private Set warehouses = new HashSet(0);

	public Product() {
	}

	public Product(String dsproduct) {
		this.dsproduct = dsproduct;
	}

	public Product(String dsproduct, String txproduct, Set prices,
			Set categories) {
		this.dsproduct = dsproduct;
		this.txproduct = txproduct;
		this.prices = prices;
		this.categories = categories;
	}

	public Integer getIdproduct() {
		return this.idproduct;
	}

	public void setIdproduct(Integer idproduct) {
		this.idproduct = idproduct;
	}

	public String getDsproduct() {
		return this.dsproduct;
	}

	public void setDsproduct(String dsproduct) {
		this.dsproduct = dsproduct;
	}

	public String getTxproduct() {
		return this.txproduct;
	}

	public void setTxproduct(String txproduct) {
		this.txproduct = txproduct;
	}

	public Set getPrices() {
		return this.prices;
	}

	public void setPrices(Set prices) {
		this.prices = prices;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}
	
	public Set getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Set warehouses) {
		this.warehouses = warehouses;
	}

}
