package com.prodigit.web.coffee.model;

// Generated 1/05/2011 12:57:56 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Warehouse implements java.io.Serializable {

	private Integer idwarehouse;
	private Integer stwarehouse;
	private String dswarehouse;
	private Set products = new HashSet(0);


	public Warehouse() {
	}

	public Warehouse(String dswarehouse) {
		this.dswarehouse = dswarehouse;
	}

	public Warehouse(String dswarehouse,  
			Set products) {
		this.dswarehouse = dswarehouse;
		this.products = products;
	}

	public Integer getIdwarehouse() {
		return this.idwarehouse;
	}

	public void setIdwarehouse(Integer idwarehouse) {
		this.idwarehouse = idwarehouse;
	}

	public String getDswarehouse() {
		return this.dswarehouse;
	}

	public void setDswarehouse(String dswarehouse) {
		this.dswarehouse = dswarehouse;
	}

	public Integer getStwarehouse() {
		return this.stwarehouse;
	}

	public void setStwarehouse(Integer stwarehouse) {
		this.stwarehouse = stwarehouse;
	}


	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}
}
